[tool.poetry]
name = "context-engine"
version = "0.1.0"
description = "Context engine for intergating LLMs with Pinecone indexes"
authors = ["Pinecone.io"]
readme = "README.md"
packages = [{include = "context_engine"}]

[tool.poetry.dependencies]
python = "^3.9"
pinecone-client = "^2.2.2"
python-dotenv = "^1.0.0"
openai = "^0.27.5"
tiktoken = "^0.3.3"
pinecone-datasets = "^0.6.0"
pydantic = "^1.10.7"
pinecone-text = "^0.5.2"

[tool.poetry.extras]
openai = ["openai", "tiktoken"]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytest = "^7.3.2"
mypy = "^1.4.1"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
