[tool.poetry]
name = "context-engine"
version = "0.1.0"
description = "Context engine for intergating LLMs with Pinecone indexes"
authors = ["Pinecone"]
readme = "README.md"
packages = [{include = "context_engine"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
