[tool.poetry]
name = "context-engine"
version = "0.1.0"
description = "Context engine for intergating LLMs with Pinecone indexes"
authors = ["Relevance Team <relevance@pinecone.io>"]
readme = "README.md"
packages = [{include = "context_engine"}]

[tool.poetry.dependencies]
python = "^3.9"
pinecone-client = "^2.2.2"
python-dotenv = "^1.0.0"
openai = "^0.27.5"
tiktoken = "^0.3.3"
pinecone-datasets = "^0.6.1"
pydantic = "^1.10.7"
pinecone-text = "^0.5.3"
flake8-pyproject = "^1.2.3"
pandas-stubs = "^2.0.3.230814"
langchain = "^0.0.188"
sse-starlette = "^1.6.5"
tabulate = "^0.9.0"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytest = "^7.3.2"
mypy = "^1.4.1"
flake8 = "^6.1.0"
pytest-html = "^3.2.0"
flake8-pyproject = "^1.2.3"
asyncio = "^3.4.3"
pytest-asyncio = "^0.14.0"
pytest-mock = "^3.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
allow_redefinition = true
exclude = ['tests']

[[tool.mypy.overrides]]
module = [
    'pinecone_text.*',
    'pinecone_datasets',
    'pinecone'
]
ignore_missing_imports = true


[tool.flake8]
per-file-ignores = [
    '*/__init__.py:F401',
]
max-line-length = 88

[tool.poetry.scripts]
context-engine = "context_engine.service.cli:cli"
service = "context_engine.service.app:start"
